notifications:
  webhooks:
    - https://webhook.commit-email.info/

matrix:
  include:
    - name: "2.7 on macOS with Xcode 12.0"
      rvm: 2.7
      os: osx
      osx_image: xcode12
    - name: "gem"
      rvm: 2.7
      install:
        - bundle install
        - rake install
      script:
        - mkdir -p tmp
        - cd tmp
        - cp -a ../test/ ./
        - test/run.rb
