notifications:
  webhooks:
    - https://webhook.commit-email.info/

matrix:
  include:
    - name: "2.7 - Xcode 12.0 - bundled"
      rvm: 2.7
      os: osx
      osx_image: xcode12
      script:
        - cd ext/fiddle
        - ruby extconf.rb --enable-bundled-libffi
        - make -j
        - cd -
        - ruby -I ext/fiddle test/run.rb
    - name: "gem"
      rvm: 2.7
      install:
        - bundle install
        - rake install
      script:
        - mkdir -p tmp
        - cd tmp
        - cp -a ../test/ ./
        - test/run.rb
