name: CI

on:
  - push
  - pull_request

jobs:
  test:
    name: >-
      ${{ matrix.os }} ${{ matrix.ruby }}
    runs-on: ${{ matrix.os }}-latest
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu
          - macos
          - windows
        ruby:
          - 2.5
          - 2.6
          - 2.7
          - head
        include:
          - { os: windows , ruby: mingw }
          - { os: windows , ruby: mswin }
        exclude:
          - { os: windows , ruby: head }

    steps:
      - uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}

      - run: bundle install

      - run: rake compile

      - run: rake build

      - run: gem install pkg/*.gem

      - run: rake test
        env:
          RUBYOPT: --disable=gems

      - name: Run test against installed gem
        # We can't use Fiddle gem with RubyInstaller because
        # RubyInstaller requires Fiddle before rubygems is loaded:
        # https://github.com/oneclick/rubyinstaller2/blob/master/lib/ruby_installer/build/dll_directory.rb#L1
        if: >-
          matrix.os != 'windows' ||
          (matrix.os == 'windows' && matrix.ruby == 'mswin')
        run: |
          ruby -run -e cp -- -pr test/ tmp/
          cd tmp
          ruby test/run.rb
